# Generated by Django 4.2.4 on 2023-10-21 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_maincategory_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategory',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='parent',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.maincategory'),
        ),
    ]
