# Generated by Django 4.2.4 on 2023-10-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_remove_maincategory_parent_id_maincategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='main_category',
        ),
        migrations.AddField(
            model_name='customuser',
            name='main_category',
            field=models.ManyToManyField(to='newapp.maincategory'),
        ),
    ]
