# Generated by Django 4.2.4 on 2024-03-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_customuser_shopname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'The Geeks Field you entered is not unique.'}, max_length=254, unique=True),
        ),
    ]
