# Generated by Django 4.2.4 on 2024-03-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email address is already in use.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
