# Generated by Django 4.2.4 on 2024-02-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_remove_order_user_id_order_phone_number_kart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='kart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='lon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
    ]
