# Generated by Django 4.2.4 on 2023-10-23 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='parent',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='newapp.maincategory'),
        ),
    ]
