# Generated by Django 4.2.4 on 2024-03-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='shopName',
            field=models.CharField(blank=True, error_messages={'unique': 'unique.'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unique_shopName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
