# Generated by Django 4.2.4 on 2023-10-24 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_alter_maincategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='level',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='location',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newapp.location'),
        ),
    ]
