# Generated by Django 4.2.4 on 2024-03-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_alter_customuser_shopname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
