# Generated by Django 4.2.4 on 2023-10-27 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_remove_location_level_remove_location_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='shopprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shopprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newapp.location'),
        ),
        migrations.AddField(
            model_name='shopprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.location'),
        ),
    ]
