# Generated by Django 4.2.4 on 2024-03-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_alter_customuser_is_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='MainCategoryImg'),
        ),
    ]
