# Generated by Django 4.2.4 on 2023-10-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_remove_customuser_city_remove_customuser_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Location',
            new_name='location',
        ),
    ]
