# Generated by Django 4.2.4 on 2024-03-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_maincategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
