# Generated by Django 4.2.4 on 2023-10-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_rename_location_customuser_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='main_category',
        ),
    ]
