# Generated by Django 4.2.4 on 2024-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_rename_company_logo_customuser_shop_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mycategory',
            name='unique_name',
            field=models.CharField(max_length=50),
        ),
    ]
