# Generated by Django 4.2.4 on 2023-10-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_remove_customuser_main_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='main_category',
            field=models.ManyToManyField(to='newapp.maincategory'),
        ),
    ]
