# Generated by Django 4.2.4 on 2023-10-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_customuser_main_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
