# Generated by Django 4.2.4 on 2024-03-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_products_aspectratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
