# Generated by Django 4.2.4 on 2023-11-01 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_delete_city_delete_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcategory',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='shopcategory',
            name='uniqu_name',
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='parent',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='newapp.shopcategory'),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='unique_name',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='parent',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='newapp.maincategory'),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='shopcategory',
            table='shopCategory',
        ),
    ]
