# Generated by Django 4.2.4 on 2023-11-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_remove_shopcategory_shop_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopCategory',
            new_name='MyCategory',
        ),
        migrations.AlterModelTable(
            name='mycategory',
            table='myCategory',
        ),
    ]
