# Generated by Django 4.2.4 on 2024-04-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_productimages_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kart',
            name='product',
        ),
        migrations.AddField(
            model_name='kart',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='product_id', to='newapp.products'),
            preserve_default=False,
        ),
    ]
