# Generated by Django 4.2.4 on 2024-04-13 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0016_remove_kart_product_id_remove_kart_shop_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='kart_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location_id',
        ),
        migrations.AddField(
            model_name='kart',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='kart',
            field=models.ManyToManyField(to='newapp.kart'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_location', to='newapp.location'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
