# Generated by Django 4.2.4 on 2024-04-14 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_remove_order_kart_id_remove_order_location_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lat',
            new_name='extra_discount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lon',
            new_name='grand_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_cost',
            new_name='originl_total_product_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_location',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='total_product_cost',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('lat', models.FloatField(default=0, null=True)),
                ('lon', models.FloatField(default=0, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('delivery_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_location', to='newapp.location')),
            ],
            options={
                'db_table': 'DeliveryAddress',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_address', to='newapp.deliveryaddress'),
        ),
    ]
