# Generated by Django 4.2.4 on 2023-12-09 14:11

from django.db import migrations, models
import newapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0017_alter_customuser_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=newapp.models.get_upload_path),
        ),
    ]
