# Generated by Django 4.2.4 on 2023-12-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_alter_customuser_unique_shopname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='backgroud_image',
            new_name='background_image',
        ),
    ]
