# Generated by Django 4.2.4 on 2024-04-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kart',
            name='status',
            field=models.CharField(blank=True, default='1', max_length=100, null=True),
        ),
    ]
