# Generated by Django 4.2.4 on 2023-12-14 16:53

from django.db import migrations, models
import newapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_rename_backgroud_image_customuser_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=newapp.models.banner_upload_path),
        ),
    ]
