# Generated by Django 4.2.4 on 2023-12-17 15:03

from django.db import migrations, models
import newapp.model_s.shopCategoryModel


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0021_alter_customuser_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=newapp.model_s.shopCategoryModel.get_upload_path),
        ),
    ]
