# Generated by Django 4.2.4 on 2024-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='source',
            field=models.TextField(blank=True, default=0),
        ),
    ]
