# Generated by Django 4.2.4 on 2024-01-08 13:09

from django.db import migrations, models
import django.db.models.deletion
import newapp.model_s.productModels


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_mycategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=newapp.model_s.productModels.get_upload_path)),
                ('aspect_ratio', models.FloatField(blank=True, null=True)),
                ('primary', models.BooleanField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='newapp.products')),
            ],
        ),
    ]
