# Generated by Django 4.2.4 on 2024-05-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0025_order_order_id_alter_order_alt_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delivery_charge',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
