# Generated by Django 4.2.4 on 2024-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0026_customuser_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
