# Generated by Django 4.2.4 on 2024-05-26 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0027_alter_customuser_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_customer', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_shop', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_likes',
                'managed': True,
            },
        ),
    ]
