# Generated by Django 4.2.4 on 2024-05-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0029_shoplikes_created_at_shoplikes_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplikes',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
