# Generated by Django 4.2.4 on 2024-05-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0030_shoplikes_is_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplikes',
            name='is_follow',
            field=models.BooleanField(default=False),
        ),
    ]
